replicaCount: 1

image:
  repository: fing/fing-agent
  tag: latest
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"

