---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-oauth
  namespace: network-services
type: Opaque
stringData:
  clientId: tsclient-xxxxxxxxxxxxxxxx
  clientSecret: tsclient-secret-xxxxxxxxxxxxxxxx
