---
apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: network-services
type: Opaque
stringData:
  client_id: tsclient-xxxxxxxxxxxxxxxx
  client_secret: tsclient-secret-xxxxxxxxxxxxxxxx
